# Generated by Django 3.2 on 2021-04-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingobject',
            options={'verbose_name': 'Объект Здание', 'verbose_name_plural': 'Объекты Здания'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Расписание встреч с клиентами', 'verbose_name_plural': 'Расписание встреч с клиентами'},
        ),
        migrations.AlterModelOptions(
            name='categoryobject',
            options={'verbose_name': 'Категория Объекта', 'verbose_name_plural': 'Категории Объектов'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Доход за месяц', 'verbose_name_plural': 'Доход за месяц'},
        ),
        migrations.AlterModelOptions(
            name='objectintobuilding',
            options={'verbose_name': 'Объект Помещение', 'verbose_name_plural': 'Объекты Помещения'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Сделка Аренды', 'verbose_name_plural': 'Сделки Аренды'},
        ),
        migrations.AlterModelOptions(
            name='sellbuy',
            options={'verbose_name': 'Сделка Купли-Продажи', 'verbose_name_plural': 'Сделки Купли-Продажи'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='Номер телефона клиента'),
        ),
    ]
