# Generated by Django 3.2 on 2021-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroi', '0002_auto_20210423_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона клиента'),
        ),
    ]
