# Generated by Django 3.2 on 2021-04-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stroi', '0003_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbuy',
            name='sell_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_object_build', to='stroi.objectintobuilding', verbose_name='Объект сделки'),
        ),
    ]
