# Generated by Django 3.2 on 2021-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroi', '0004_alter_sellbuy_sell_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectintobuilding',
            name='price_category',
            field=models.CharField(blank=True, choices=[('Эконом', 'Эконом'), ('Комфорт', 'Комфорт'), ('Люкс', 'Люкс'), ('Премиум', 'Премиум')], default=None, max_length=20, null=True, verbose_name='Ценовая категория'),
        ),
    ]
