# Generated by Django 3.2 on 2021-04-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stroi', '0005_alter_objectintobuilding_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingobject',
            name='region',
            field=models.CharField(choices=[('Чуйская', 'Чуйская'), ('Таласская', 'Таласская'), ('Баткенская', 'Баткенская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Ошская', 'Ошская'), ('Джалал-Абадская', 'Джалал-Абадская')], max_length=20, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='objectintobuilding',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_category', to='stroi.categoryobject', verbose_name='Категория объекта'),
        ),
    ]
